### ISSUE TITLE
Sistema de Notificações

### ISSUE THREAD

**Issue by gabrielsb18** [gabrielsb18/PI-Mobile#25]
-Configurar sistema de notificações de lembretes em tempo real;
-Conectar com API para enviar notificações relevantes;
-Implementar lógica para atualizar a listagem de lembretes.

**Comment by RBDSVIANA** [comment]
![Image](https://github.com/gabrielsb18/PI_Mobile/assets/142273777/55027c18-3b0e-48df-94c0-b6339b697834)
![Image](https://github.com/gabrielsb18/PI_Mobile/assets/142273777/586fc6a5-064b-405e-b1ce-6922c2a1e6d6)
![Image](https://github.com/gabrielsb18/PI_Mobile/assets/142273777/078afc5d-d7e4-47b2-ad3a-b906f270407d)
![Image](https://github.com/gabrielsb18/PI_Mobile/assets/142273777/c295e503-0f58-4eb6-959a-46ea87296a77)
